# Generated by Django 4.2.16 on 2025-05-02 13:42

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalmealcontentpage',
            name='body',
            field=wagtail.fields.StreamField([('intro_text', 1), ('heading', 2), ('paragraph', 3), ('list', 5), ('image', 6), ('call_to_action', 11)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'List'}), 5: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ul'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'document-link', 'link', 'ol', 'ul']}), 9: ('wagtail.blocks.URLBlock', (), {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('#BFE2E0', 'Blue'), ('#C8C1E1', 'Purple'), ('#F7B17B', 'Orange'), ('#F5E165', 'Yellow'), ('#D6E297', 'Lightgreen'), ('#9BCEA4', 'Green'), ('#FFFFFF', 'White'), ('#212529', 'Black')]}), 11: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8), ('cta_linktext', 7), ('cta_link', 9), ('background_color', 10), ('text_color', 10), ('button_background_color', 10), ('button_text_color', 10)]], {})}),
        ),
    ]
