# Generated by Django 5.2.6 on 2026-01-09 13:52

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokWatchHistoryStatistics',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('scope', models.CharField(choices=[('FULL', 'Full History'), ('INTERVAL', 'Date range')], help_text='Indicates whether statistics are computed on full dataset or on data in a specific interval.', max_length=20)),
                ('interval_start', models.DateTimeField(blank=True, null=True)),
                ('interval_end', models.DateTimeField(blank=True, null=True)),
                ('date_first_video', models.DateTimeField(blank=True, null=True)),
                ('date_last_video', models.DateTimeField(blank=True, null=True)),
                ('total_videos', models.IntegerField(blank=True, null=True)),
                ('total_videos_unique', models.IntegerField(blank=True, null=True)),
                ('videos_per_day', models.FloatField(blank=True, null=True)),
                ('total_days_with_activity', models.IntegerField(blank=True, help_text='Number of days on which some watch activity was recorded', null=True)),
                ('peak_day_date', models.DateField(blank=True, null=True)),
                ('peak_day_video_count', models.PositiveIntegerField(blank=True, null=True)),
                ('peak_hour', models.PositiveIntegerField(blank=True, help_text='Hour of day (0-23) with most video views', null=True, validators=[django.core.validators.MaxValueValidator(23)])),
                ('session_threshold_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds of inactivity that define session boundaries', null=True)),
                ('avg_session_duration_seconds', models.FloatField(blank=True, help_text='Mean session duration in seconds', null=True)),
                ('avg_videos_per_session', models.FloatField(blank=True, null=True)),
                ('avg_seconds_per_video', models.FloatField(blank=True, null=True)),
                ('top_video_id', models.CharField(blank=True, max_length=25, null=True)),
                ('top_video_seen_count', models.PositiveIntegerField(blank=True, null=True)),
                ('top_video_last_seen_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TikTok Watch History Statistics',
                'verbose_name_plural': 'TikTok Watch History Statistics',
                'ordering': ['-date_created'],
            },
        ),
    ]
