# Generated by Django 5.2.6 on 2026-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydigitalmeal_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokwatchhistorystatistics',
            name='top_video_id',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
