# Generated by Django 5.2.10 on 2026-01-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_participation', '0002_alter_participant_project'),
        ('mydigitalmeal_profiles', '0001_initial'),
        ('mydigitalmeal_statistics', '0002_alter_tiktokwatchhistorystatistics_top_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokwatchhistorystatistics',
            name='ddm_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_wh_statistics', to='ddm_participation.participant'),
        ),
        migrations.AddField(
            model_name='tiktokwatchhistorystatistics',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_wh_statistics', to='mydigitalmeal_profiles.mdmprofile'),
        ),
    ]
