# Generated by Django 5.2.10 on 2026-01-14 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm_participation', '0002_alter_participant_project'),
        ('mydigitalmeal_profiles', '0001_initial'),
        ('mydigitalmeal_statistics', '0003_tiktokwatchhistorystatistics_ddm_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokwatchhistorystatistics',
            name='ddm_participant',
        ),
        migrations.RemoveField(
            model_name='tiktokwatchhistorystatistics',
            name='profile',
        ),
        migrations.CreateModel(
            name='StatisticsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETRY', 'Retry'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('status_detail', models.TextField()),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_requests', to='ddm_participation.participant')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_requests', to='mydigitalmeal_profiles.mdmprofile')),
            ],
            options={
                'verbose_name': 'Statistics Request',
                'verbose_name_plural': 'Statistics Requests',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='tiktokwatchhistorystatistics',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiktok_wh_statistics', to='mydigitalmeal_statistics.statisticsrequest'),
        ),
    ]
