# Generated by Django 5.2.10 on 2026-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydigitalmeal_statistics', '0004_remove_tiktokwatchhistorystatistics_ddm_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokwatchhistorystatistics',
            name='scroll_threshold_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiktokwatchhistorystatistics',
            name='scroll_threshold_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticsrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RETRY', 'Retry'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=20),
        ),
    ]
