# Generated by Django 5.2.11 on 2026-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydigitalmeal_statistics', '0005_tiktokwatchhistorystatistics_scroll_threshold_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokwatchhistorystatistics',
            name='date_hour_activity_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
