# Generated by Django 3.2.19 on 2023-08-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='end_date',
        ),
        migrations.AddField(
            model_name='classroom',
            name='instruction_format',
            field=models.CharField(choices=[], default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='school_level',
            field=models.CharField(choices=[], default='default', max_length=2, verbose_name='Schulstufe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='school_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='track',
            field=models.CharField(choices=[], default='default', max_length=20),
            preserve_default=False,
        ),
    ]
