# Generated by Django 3.2.19 on 2023-08-14 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0003_auto_20230809_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='ddm_project_id',
        ),
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='instruction_format',
            field=models.CharField(choices=[('regular', 'Regulärer Unterricht'), ('optional', 'Wahlpflichtfach, Freifach, Kurs, o.ä.'), ('special', 'Sonderwoche o.ä.')], max_length=20, verbose_name='Unterrichtsformat'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='pool_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school_level',
            field=models.CharField(choices=[('primary', 'Primarstufe'), ('secondary', 'Sekundarstufe I (z.B. Sekundar- oder Realschule, Bezirksschule oder Untergymnasium)'), ('gymnasium', 'Gymnasiale Maturitätsschulen'), ('specialised sec.', 'Fachmittelschulen'), ('vocational', 'Berufsschulen und Berufsmaturitätsschulen'), ('pedagogical', 'Pädagogische Hochschulen'), ('specialised tert.', 'Fachhochschulen und Höhere Fachhochschulen'), ('university', 'Universitäre Hochschulen'), ('other', 'Andere')], max_length=20, verbose_name='Schulstufe'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Schuljahr'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(choices=[('languages', 'Sprachunterricht (Deutsch, Französisch, Englisch, etc.)'), ('informatics and media', 'Medien- und Informatikunterricht, Medienerziehung o.ä.'), ('ethics, religion', '"Ethik, Religion, Gemeinschaft" (ERG), Ethikunterricht oder Gesellschaftskunde'), ('general education', '"Allgemeinbildender Unterricht" (ABU), o.ä.'), ('math, nature and technics', 'Mathematik oder "Natur und Technik"'), ('society, history, geography', '"Räume, Zeiten, Gesellschaften" (RZG), Geschichte, Geografie, o.ä.'), ('other', 'Anderes')], max_length=100, verbose_name='Unterrichtsfach'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_meal.module')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_meal.track', verbose_name='Track'),
        ),
    ]
