# Generated by Django 3.2.19 on 2024-01-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0003_auto_20240122_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='ddm_project_id',
            field=models.CharField(default='notset', max_length=255),
            preserve_default=False,
        ),
    ]
