# Generated by Django 3.2.19 on 2024-01-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0004_track_ddm_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='ddm_api_endpoint',
            field=models.URLField(default='https://notset.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='ddm_api_token',
            field=models.CharField(default='notset', max_length=40),
            preserve_default=False,
        ),
    ]
