# Generated by Django 3.2.19 on 2024-02-05 15:09

import digital_meal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0005_auto_20240122_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='active',
        ),
        migrations.AddField(
            model_name='classroom',
            name='expiry_date',
            field=models.DateTimeField(default=digital_meal.models.now_plus_six_months),
        ),
    ]
