# Generated by Django 3.2.19 on 2024-02-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0006_auto_20240205_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='pool_id',
            new_name='external_id',
        ),
    ]
