# Generated by Django 4.2.10 on 2024-03-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0008_auto_20240222_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='external_id',
            new_name='class_id',
        ),
    ]
