# Generated by Django 4.2.26 on 2025-12-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portability', '0003_tiktokdatarequest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OAuthToken',
            new_name='OAuthStateToken',
        ),
    ]
