# Generated by Django 4.2.26 on 2026-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portability', '0004_rename_oauthtoken_oauthstatetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdatarequest',
            name='status',
            field=models.CharField(default='not polled', max_length=20),
        ),
    ]
