# Generated by Django 4.2.26 on 2025-12-29 16:39

from django.db import migrations, models
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portability', '0002_tiktokaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=250, verbose_name='ID of TikTok user')),
                ('request_id', models.BigIntegerField(unique=True, verbose_name='ID of data request')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_polled', models.DateTimeField(null=True)),
                ('status', models.CharField(default='not-polled', max_length=20)),
                ('download_attempted', models.BooleanField(default=False)),
                ('download_succeeded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AlterField(
            model_name='tiktokaccesstoken',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tiktokaccesstoken',
            name='token',
            field=encrypted_fields.fields.EncryptedTextField(max_length=250),
        ),
    ]
