# Generated by Django 5.2.11 on 2026-02-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portability', '0005_alter_tiktokdatarequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstatetoken',
            name='context',
            field=models.CharField(choices=[('DM_EDU', 'Digital Meal Education'), ('MY_DM', 'My Digital Meal')], default='DM_EDU', help_text='Context of the token (My DM or DM Education)', max_length=20),
        ),
    ]
