# Generated by Django 5.2.17 on 2026-09-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ddm_projects', '0010_alter_donationproject_custom_uploader_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_reminder', models.BooleanField(default=False)),
                ('show_report_invite_link', models.BooleanField(default=False)),
                ('report_invite_link', models.URLField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_project', to='ddm_projects.donationproject')),
            ],
        ),
    ]
