# Generated by Django 5.2.17 on 2026-09-21 13:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydigitalmeal_studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyproject',
            name='portability_briefing',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Porability Briefing Text'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='report_invite_link',
            field=models.URLField(blank=True),
        ),
    ]
