# Generated by Django 4.2.10 on 2024-03-26 13:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/%Y/%m/')),
                ('materials_text', ckeditor.fields.RichTextField()),
                ('ddm_path', models.URLField()),
                ('ddm_project_id', models.CharField(max_length=255)),
                ('data_endpoint', models.URLField()),
                ('overview_endpoint', models.URLField()),
                ('ddm_api_token', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_parameter', models.SlugField(max_length=5)),
                ('description', models.TextField()),
                ('materials_text', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=False)),
                ('main_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.maintrack')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='sub_tracks',
            field=models.ManyToManyField(to='tool.subtrack'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.maintrack', verbose_name='Main Track'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
