# Generated by Django 4.2.16 on 2024-11-28 09:41

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_maintrack_subtrack_classroom_sub_tracks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='sub_tracks',
            field=models.ManyToManyField(blank=True, to='tool.subtrack'),
        ),
        migrations.AlterField(
            model_name='maintrack',
            name='materials_text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='subtrack',
            name='materials_text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
