# Generated by Django 4.2.16 on 2025-02-20 14:45

import digital_meal.tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_classroom_sub_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='url_id',
            field=models.SlugField(default=None, max_length=10, null=True),
        ),
    ]
