# Generated by Django 4.2.16 on 2025-04-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_basemodule_submodule_remove_subtrack_main_track_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemodule',
            options={'verbose_name': 'Base Module'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Classroom'},
        ),
        migrations.AlterModelOptions(
            name='submodule',
            options={'verbose_name': 'Sub Module'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher'},
        ),
        migrations.AddField(
            model_name='basemodule',
            name='report_prefix',
            field=models.SlugField(default='placeholder_'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='ddm_path',
            field=models.URLField(verbose_name='DDM path'),
        ),
        migrations.AlterField(
            model_name='basemodule',
            name='ddm_project_id',
            field=models.CharField(max_length=255, verbose_name='DDM project id'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='base_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.basemodule', verbose_name='Base Module'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='url_parameter',
            field=models.SlugField(max_length=5, verbose_name='URL parameter'),
        ),
    ]
