# Generated by Django 3.2.19 on 2024-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0007_rename_pool_id_classroom_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='ddm_api_endpoint',
            new_name='data_endpoint',
        ),
        migrations.AddField(
            model_name='track',
            name='overview_endpoint',
            field=models.URLField(default='http://something.ch'),
            preserve_default=False,
        ),
    ]
