# Generated by Django 4.2.16 on 2025-05-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_basemodule_options_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodule',
            name='test_class_url_id',
            field=models.ForeignKey(blank=True, help_text='The url_id of the class that is used to collect the test cases for this module (needed for the individual report to work in the test participation).', null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.classroom'),
        ),
    ]
