# Generated by Django 4.2.16 on 2025-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_basemodule_test_class_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodule',
            name='test_class_url_id',
            field=models.CharField(blank=True, help_text='The url_id of the class that is used to collect the test cases for this module (needed for the individual report to work in the test participation).', max_length=10, null=True),
        ),
    ]
