# Generated by Django 4.2.16 on 2025-05-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_alter_basemodule_test_class_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_id',
        ),
    ]
