# Generated by Django 4.2.16 on 2025-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_remove_classroom_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_test_participation_class',
            field=models.BooleanField(default=False, help_text='Select if this class is used to collect test participations.'),
        ),
    ]
