# Generated by Django 4.2.10 on 2024-03-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0010_classroom_report_ref_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='participant_ids',
        ),
    ]
