# Generated by Django 4.2.10 on 2024-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_meal', '0011_remove_classroom_participant_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='agb_agree',
            field=models.BooleanField(default=False, verbose_name='AGB Einverständniserklärung'),
        ),
    ]
